"""
Django settings for myportfolio project.

Generated by 'django-admin startproject' using Django 5.2.8.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-u3kxyegl7ee#p#rq6_4%smk^j-e&nve*ngl3m1+ws*)5f7lge7'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'clinic',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    
    'clinic.middleware.DatabaseRoleMiddleware', 
]

DATABASE_ROUTERS = []

ROOT_URLCONF = 'myportfolio.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'myportfolio.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

# from decouple import config

# settings.py - добавляем новые подключения
DATABASES = {
    'default': {  # Основное подключение (для миграций и админа)
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': 'clinic',
        'USER': 'bog',
        'PASSWORD': '391440',
        'HOST': '127.0.0.1',
        'PORT': '5432'
    },
    # 'doctor_db': {  # Подключение от лица врача
    #     'ENGINE': 'django.db.backends.postgresql',
    #     'NAME': 'clinic',
    #     'USER': 'doctor_role',    # Роль из твоего proj-roles.sql
    #     'PASSWORD': 'doctor_pass_123',  # Нужно задать пароль для роли
    #     'HOST': '127.0.0.1',
    #     'PORT': '5432',
    #     'OPTIONS': {
    #         'options': '-c search_path=public'
    #     }
    # },
    # 'patient_db': {  # Подключение от лица пациента
    #     'ENGINE': 'django.db.backends.postgresql',
    #     'NAME': 'clinic',
    #     'USER': 'patient_role',
    #     'PASSWORD': 'patient_pass_123',
    #     'HOST': '127.0.0.1',
    #     'PORT': '5432',
    #     'OPTIONS': {
    #         'options': '-c default_transaction_read_only=on'  # Только чтение!
    #     }
    # },
    # 'registrar_db': {  # Для регистраторов
    #     'ENGINE': 'django.db.backends.postgresql',
    #     'NAME': 'clinic',
    #     'USER': 'registrar',
    #     'PASSWORD': 'registrar_pass_123',
    #     'HOST': '127.0.0.1',
    #     'PORT': '5432'
    # }
}





# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'ru-ru'

TIME_ZONE = 'Europe/Moscow'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
# settings.py

# Куда перенаправлять после успешного входа (используем name='profile' из urls.py)
LOGIN_REDIRECT_URL = 'profile'

# Куда перенаправлять после выхода (используем name='home')
LOGOUT_REDIRECT_URL = 'home'

# Где находится страница входа (на случай, если неавторизованный юзер попытается зайти в ЛК)
LOGIN_URL = 'login'