name: CI/CD Build and Push

on:
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to Gitea Container Registry
        uses: docker/login-action@v2
        with:
          registry: git.klsh.ru
          username: team2
          password: ${{ secrets.RUNNER_TOKEN }}

      # 1. Сборка Django Монолита
      - name: Build and Push Django Monolith
        run: |
          docker build -t git.klsh.ru/team2/project-clinic:django \
                       -f Dockerfile .
          docker push git.klsh.ru/team2/project-clinic:django

      # 2. Сборка notify_service
      - name: Build and Push Notify Service
        run: |
          docker build -t git.klsh.ru/team2/project-clinic:notify \
                       -f notify_service/Dockerfile notify_service/
          docker push git.klsh.ru/team2/project-clinic:notify

      # 3. Сборка pdf_service
      - name: Build and Push PDF Service
        run: |
          docker build -t git.klsh.ru/team2/project-clinic:pdf \
                       -f pdf_service/Dockerfile pdf_service/
          docker push git.klsh.ru/team2/project-clinic:pdf