# Generated by Django 5.2.8 on 2025-12-04 11:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Diagnosis',
            fields=[
                ('id_diag', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200, verbose_name='Диагноз')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Диагноз',
                'verbose_name_plural': 'Диагнозы',
            },
        ),
        migrations.CreateModel(
            name='Drug',
            fields=[
                ('id_drug', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200, verbose_name='Название')),
                ('moment', models.CharField(choices=[('before', 'До приема'), ('during', 'Во время приема'), ('after', 'После приема')], max_length=10)),
            ],
            options={
                'verbose_name': 'Лекарство',
                'verbose_name_plural': 'Лекарства',
            },
        ),
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id_doc', models.AutoField(primary_key=True, serialize=False)),
                ('fname', models.CharField(max_length=150, verbose_name='Имя')),
                ('lname', models.CharField(max_length=150, verbose_name='Фамилия')),
                ('specialization', models.CharField(max_length=200, verbose_name='Специализация')),
                ('region', models.IntegerField(verbose_name='Регион')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Аккаунт для входа')),
            ],
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id_rec', models.AutoField(primary_key=True, serialize=False)),
                ('visit_time', models.DateTimeField(verbose_name='Дата и время визита')),
                ('cabinet', models.IntegerField(verbose_name='Кабинет')),
                ('doctor', models.ForeignKey(db_column='id_doc', on_delete=django.db.models.deletion.CASCADE, to='clinic.doctor', verbose_name='Врач')),
            ],
            options={
                'verbose_name': 'Запись на приём',
                'verbose_name_plural': 'Записи на приём',
            },
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id_pat', models.AutoField(primary_key=True, serialize=False)),
                ('fname', models.CharField(max_length=150, verbose_name='Имя')),
                ('lname', models.CharField(max_length=150, verbose_name='Фамилия')),
                ('birth_date', models.DateField(verbose_name='Дата рождения')),
                ('region', models.IntegerField(verbose_name='Регион')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Аккаунт для входа')),
            ],
        ),
        migrations.CreateModel(
            name='HistoryAppointment',
            fields=[
                ('id_change', models.AutoField(primary_key=True, serialize=False)),
                ('visit_time', models.DateTimeField(verbose_name='Дата и время визита')),
                ('cabinet', models.IntegerField(verbose_name='Кабинет')),
                ('id_doc', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='clinic.doctor', verbose_name='Врач')),
                ('id_rec', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='clinic.appointment', verbose_name='Запись')),
                ('id_pat', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='clinic.patient', verbose_name='Пациент')),
            ],
            options={
                'verbose_name': 'История изменения данных',
                'verbose_name_plural': 'История изменения данных',
            },
        ),
        migrations.AddField(
            model_name='appointment',
            name='patient',
            field=models.ForeignKey(db_column='id_pat', on_delete=django.db.models.deletion.CASCADE, to='clinic.patient', verbose_name='Пациент'),
        ),
        migrations.CreateModel(
            name='Prescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('frequency', models.IntegerField(verbose_name='Частота применения')),
                ('duration', models.DurationField(verbose_name='Продолжительность')),
                ('treatment', models.TextField(verbose_name='Лечение')),
                ('id_diag', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='clinic.diagnosis', verbose_name='Диагноз')),
                ('id_drug', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='clinic.drug', verbose_name='Лекарство')),
                ('id_rec', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='clinic.appointment', verbose_name='Запись')),
            ],
            options={
                'verbose_name': 'Рецепт',
                'verbose_name_plural': 'Рецепты',
                'unique_together': {('id_rec', 'id_drug')},
            },
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.IntegerField(choices=[(1, 'Понедельник'), (2, 'Вторник'), (3, 'Среда'), (4, 'Четверг'), (5, 'Пятница'), (6, 'Суббота'), (7, 'Воскресенье')], verbose_name='День недели')),
                ('time_start', models.TimeField(verbose_name='Начало приёма')),
                ('time_end', models.TimeField(verbose_name='Конец приёма')),
                ('interval', models.DurationField(default='00:20:00', verbose_name='Интервал')),
                ('doctor', models.ForeignKey(db_column='id_doc', on_delete=django.db.models.deletion.CASCADE, to='clinic.doctor', verbose_name='Врач')),
            ],
            options={
                'verbose_name': 'Пункт расписания',
                'verbose_name_plural': 'Расписания',
                'unique_together': {('doctor', 'day', 'time_start')},
            },
        ),
    ]
