# Generated by Django 5.2.8 on 2025-12-16 13:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalystStatsView',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('fname', models.CharField(max_length=150)),
                ('lname', models.CharField(max_length=150)),
                ('specialization', models.CharField(max_length=200)),
                ('appointment_count', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Статистика за месяц',
                'db_table': 'static_per_month',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DoctorFutureAppointmentView',
            fields=[
                ('id_rec', models.IntegerField(primary_key=True, serialize=False)),
                ('visit_time', models.DateTimeField()),
                ('cabinet', models.IntegerField()),
                ('patient_name', models.CharField(max_length=300)),
                ('birth_date', models.DateField()),
            ],
            options={
                'db_table': 'view_doctor_future_appointments',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DoctorPastAppointmentView',
            fields=[
                ('id_rec', models.IntegerField(primary_key=True, serialize=False)),
                ('visit_time', models.DateTimeField()),
                ('patient_name', models.CharField(max_length=300)),
                ('has_prescription', models.BooleanField()),
            ],
            options={
                'db_table': 'view_doctor_past_appointments',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PatientHistoryView',
            fields=[
                ('id_rec', models.IntegerField(primary_key=True, serialize=False)),
                ('visit_time', models.DateTimeField()),
                ('doctor_info', models.CharField(max_length=300)),
                ('cabinet', models.IntegerField()),
                ('diagnosis', models.CharField(max_length=200, null=True)),
                ('drug_name', models.CharField(max_length=200, null=True)),
                ('treatment', models.TextField(null=True)),
                ('frequency', models.IntegerField(null=True)),
                ('duration', models.DurationField(null=True)),
            ],
            options={
                'db_table': 'view_patient_history',
                'managed': False,
            },
        ),
        migrations.AlterField(
            model_name='historyappointment',
            name='id_doc',
            field=models.ForeignKey(blank=True, db_column='id_doc', null=True, on_delete=django.db.models.deletion.SET_NULL, to='clinic.doctor', verbose_name='Врач'),
        ),
        migrations.AlterField(
            model_name='historyappointment',
            name='id_pat',
            field=models.ForeignKey(blank=True, db_column='id_pat', null=True, on_delete=django.db.models.deletion.SET_NULL, to='clinic.patient', verbose_name='Пациент'),
        ),
        migrations.AlterField(
            model_name='historyappointment',
            name='id_rec',
            field=models.ForeignKey(blank=True, db_column='id_rec', null=True, on_delete=django.db.models.deletion.SET_NULL, to='clinic.appointment', verbose_name='Запись'),
        ),
    ]
