# Generated by Django 5.2.8 on 2025-12-16 14:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0002_analyststatsview_doctorfutureappointmentview_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='historyappointment',
            options={'managed': False, 'verbose_name': 'История изменения данных', 'verbose_name_plural': 'История изменения данных'},
        ),
    ]
