# Generated by Django 5.2.8 on 2025-12-17 11:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0003_alter_historyappointment_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prescription',
            name='id_rec',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='clinic.appointment', verbose_name='Запись'),
        ),
    ]
