# Generated by Django 5.2.8 on 2026-04-04 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0004_alter_prescription_id_rec'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='email',
            field=models.EmailField(default='lasenkob213@gmail.com', max_length=254, verbose_name='Email пациента'),
        ),
    ]
